// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TruekeBogotaSolidario.Datos.Contexto;

#nullable disable

namespace TruekeBogotaSolidario.Datos.Migraciones
{
    [DbContext(typeof(TruekeDbContext))]
    [Migration("20261002174413_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.AuditoriaEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detalle")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ObjetivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ObjetivoTipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("FechaUtc");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Calificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalificadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comentario")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("ComentarioOculto")
                        .HasColumnType("bit");

                    b.Property<int>("Estrellas")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoOcultamiento")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("CalificadoId", "FechaUtc");

                    b.HasIndex("SolicitudId", "AutorId")
                        .IsUnique();

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Prendas, zapatos y accesorios",
                            NombreCategoria = "Ropa y calzado"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Libros, textos escolares y útiles",
                            NombreCategoria = "Libros y papelería"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Aparatos para el hogar",
                            NombreCategoria = "Electrodomésticos"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Decoración, menaje y muebles",
                            NombreCategoria = "Hogar y muebles"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Computadores, celulares y accesorios",
                            NombreCategoria = "Tecnología"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Juguetes y artículos infantiles",
                            NombreCategoria = "Juguetes y niños"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Todo lo demás",
                            NombreCategoria = "Otros"
                        });
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Comentario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaOculto")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoOcultamiento")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("PublicacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId", "FechaUtc");

                    b.HasIndex("PublicacionId", "EstaOculto", "FechaUtc");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Conversacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadaUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DuenioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PublicacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SolicitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UltimoMensajeUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PublicacionId");

                    b.HasIndex("SolicitudId")
                        .IsUnique();

                    b.HasIndex("DuenioId", "UltimoMensajeUtc");

                    b.HasIndex("SolicitanteId", "UltimoMensajeUtc");

                    b.ToTable("Conversaciones");
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Denuncia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DenuncianteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detalle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaResolucionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModeradorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NotaResolucion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("ObjetivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Estado", "FechaUtc");

                    b.HasIndex("DenuncianteId", "Tipo", "ObjetivoId")
                        .IsUnique();

                    b.HasIndex("Tipo", "ObjetivoId", "Estado");

                    b.ToTable("Denuncias");
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Favorito", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PublicacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId", "PublicacionId");

                    b.HasIndex("PublicacionId");

                    b.HasIndex("UsuarioId", "FechaUtc");

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Mensaje", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaOculto")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LeidoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoOcultamiento")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId", "FechaUtc");

                    b.HasIndex("ConversacionId", "FechaUtc");

                    b.HasIndex("ConversacionId", "AutorId", "LeidoUtc");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LeidaUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("RecursoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "LeidaUtc", "FechaUtc");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DocumentoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaResolucionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MontoCop")
                        .HasColumnType("int");

                    b.Property<string>("NotaInterna")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ProveedorTransaccionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("PublicacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PuntosCanjeados")
                        .HasColumnType("int");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorTransaccionId")
                        .IsUnique()
                        .HasFilter("[ProveedorTransaccionId] IS NOT NULL");

                    b.HasIndex("Referencia")
                        .IsUnique();

                    b.HasIndex("Estado", "FechaUtc");

                    b.HasIndex("UsuarioId", "Concepto", "Estado");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Publicacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("DestacadaHasta")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstaOculta")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaEdicion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Latitud")
                        .HasColumnType("float");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<double?>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MotivoCancelacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MotivoOcultamiento")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("PrecioReferenciaCop")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PropietarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("PropietarioId");

                    b.HasIndex("Estado", "EstaOculta");

                    b.HasIndex("Latitud", "Longitud");

                    b.ToTable("Publicaciones");
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.SesionRefresh", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ConDosFactores")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiraFamiliaUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiraUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReemplazadoPorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevocadoUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiraUtc");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId", "RevocadoUtc");

                    b.ToTable("SesionesRefresh");
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Solicitud", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConfirmadaPorDuenioUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmadaPorSolicitanteUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaAceptacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierreUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("PublicacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SolicitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PublicacionId", "Estado");

                    b.HasIndex("SolicitanteId", "Estado");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.TokenUsoUnico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiraUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Proposito")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("UsadoUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiraUtc");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId", "Proposito", "CreadoUtc");

                    b.ToTable("TokensUsoUnico");
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Transaccion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("OferenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PublicacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("PuntosOtorgadosOferente")
                        .HasColumnType("bit");

                    b.Property<bool>("PuntosOtorgadosReceptor")
                        .HasColumnType("bit");

                    b.Property<Guid>("ReceptorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OferenteId", "FechaUtc");

                    b.HasIndex("ReceptorId", "FechaUtc");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("datetime2");

                    b.Property<int>("CalificacionesSuma")
                        .HasColumnType("int");

                    b.Property<int>("CalificacionesTotal")
                        .HasColumnType("int");

                    b.Property<string>("ClaveHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CodigosRecuperacionHash")
                        .HasMaxLength(700)
                        .IsUnicode(false)
                        .HasColumnType("varchar(700)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<bool>("CorreoVerificado")
                        .HasColumnType("bit");

                    b.Property<int>("DestacadosGratisRestantes")
                        .HasColumnType("int");

                    b.Property<string>("DocumentoVerificacionUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("DosFactoresActivo")
                        .HasColumnType("bit");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit");

                    b.Property<bool>("EstaSuspendido")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoVerificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaAceptacionPolitica")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimientoSuscripcion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVerificacionCorreo")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoogleSub")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("IntentosFallidosLogin")
                        .HasColumnType("int");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("MotivoRechazoVerificacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MotivoSuspension")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PoliticaDatosVersion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Reputacion")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SaldoEcoPuntos")
                        .HasColumnType("int");

                    b.Property<string>("SecretoDosFactoresCifrado")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("SuspendidoHasta")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoCuenta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalComprasRealizadas")
                        .HasColumnType("int");

                    b.Property<int>("TotalDonacionesRealizadas")
                        .HasColumnType("int");

                    b.Property<int>("TotalTruekesCompletados")
                        .HasColumnType("int");

                    b.Property<long>("UltimoPasoDosFactores")
                        .HasColumnType("bigint");

                    b.Property<int>("VersionSeguridad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("EstaSuspendido");

                    b.HasIndex("EstadoVerificacion");

                    b.HasIndex("GoogleSub")
                        .IsUnique()
                        .HasFilter("[GoogleSub] IS NOT NULL");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Calificacion", b =>
                {
                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CalificadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Solicitud", null)
                        .WithMany()
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Comentario", b =>
                {
                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Publicacion", "Publicacion")
                        .WithMany()
                        .HasForeignKey("PublicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Publicacion");
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Conversacion", b =>
                {
                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Usuario", "Duenio")
                        .WithMany()
                        .HasForeignKey("DuenioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Publicacion", null)
                        .WithMany()
                        .HasForeignKey("PublicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Usuario", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Duenio");

                    b.Navigation("Solicitante");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Denuncia", b =>
                {
                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("DenuncianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Favorito", b =>
                {
                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Publicacion", null)
                        .WithMany()
                        .HasForeignKey("PublicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Mensaje", b =>
                {
                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Conversacion", "Conversacion")
                        .WithMany()
                        .HasForeignKey("ConversacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversacion");
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Notificacion", b =>
                {
                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Pago", b =>
                {
                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Publicacion", b =>
                {
                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Usuario", "Propietario")
                        .WithMany()
                        .HasForeignKey("PropietarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("TruekeBogotaSolidario.Datos.Entidades.ImagenPublicacion", "Imagenes", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Orden")
                                .HasColumnType("int");

                            b1.Property<Guid>("PublicacionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.HasKey("Id");

                            b1.HasIndex("PublicacionId");

                            b1.ToTable("PublicacionImagenes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PublicacionId");
                        });

                    b.Navigation("Categoria");

                    b.Navigation("Imagenes");

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.SesionRefresh", b =>
                {
                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Solicitud", b =>
                {
                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Publicacion", "Publicacion")
                        .WithMany()
                        .HasForeignKey("PublicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Usuario", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Publicacion");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.TokenUsoUnico", b =>
                {
                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TruekeBogotaSolidario.Datos.Entidades.Transaccion", b =>
                {
                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("OferenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruekeBogotaSolidario.Datos.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ReceptorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
