<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TruekeBogotaSolidario.Datos</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <!-- Capa DAL: SOLO aquí viven los paquetes de EF Core -->
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.20">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.12" />
  </ItemGroup>

  <!-- Catálogo oficial de departamentos y municipios (DANE - DIVIPOLA): datos de referencia de solo lectura -->
  <ItemGroup>
    <EmbeddedResource Include="Recursos\divipola.json" LogicalName="TruekeBogotaSolidario.Datos.divipola.json" />
  </ItemGroup>

</Project>
